[all_hosts] # Định nghĩa nhóm (group) máy chủ có tên là all_hosts
target1 ansible_ssh_host=3.26.216.89 ansible_python_interpreter=/usr/bin/python3 # xác định máy chủ "target1" với địa chỉ IP là "10.32.3.131"
target2 ansible_ssh_host=16.176.28.2 ansible_python_interpreter=/usr/bin/python3 # xác định máy chủ "target2" với địa chỉ IP là "10.32.3.132"

[webservers] # Định nghĩa nhóm máy chủ được chọn làm web servers
target1

[loadbalancingservers] # Định nghĩa nhóm máy chủ được chọn làm load balancing servers
target2
